/*
INSERT INTO CARTE VALUES ('COEUR', '1');
INSERT INTO CARTE VALUES ('COEUR', '2');
INSERT INTO CARTE VALUES ('COEUR', '3');
INSERT INTO CARTE VALUES ('COEUR', '4');
INSERT INTO CARTE VALUES ('COEUR', '5');
INSERT INTO CARTE VALUES ('COEUR', '6');
INSERT INTO CARTE VALUES ('COEUR', '7');
INSERT INTO CARTE VALUES ('COEUR', '8');
INSERT INTO CARTE VALUES ('COEUR', '9');
INSERT INTO CARTE VALUES ('COEUR', '10');
INSERT INTO CARTE VALUES ('COEUR', 'VALET');
INSERT INTO CARTE VALUES ('COEUR', 'DAME');
INSERT INTO CARTE VALUES ('COEUR', 'ROI');


INSERT INTO CARTE VALUES ('PIQUE', '1');
INSERT INTO CARTE VALUES ('PIQUE', '2');
INSERT INTO CARTE VALUES ('PIQUE', '3');
INSERT INTO CARTE VALUES ('PIQUE', '4');
INSERT INTO CARTE VALUES ('PIQUE', '5');
INSERT INTO CARTE VALUES ('PIQUE', '6');
INSERT INTO CARTE VALUES ('PIQUE', '7');
INSERT INTO CARTE VALUES ('PIQUE', '8');
INSERT INTO CARTE VALUES ('PIQUE', '9');
INSERT INTO CARTE VALUES ('PIQUE', '10');
INSERT INTO CARTE VALUES ('PIQUE', 'VALET');
INSERT INTO CARTE VALUES ('PIQUE', 'DAME');
INSERT INTO CARTE VALUES ('PIQUE', 'ROI');


INSERT INTO CARTE VALUES ('TREFLE', '1');
INSERT INTO CARTE VALUES ('TREFLE', '2');
INSERT INTO CARTE VALUES ('TREFLE', '3');
INSERT INTO CARTE VALUES ('TREFLE', '4');
INSERT INTO CARTE VALUES ('TREFLE', '5');
INSERT INTO CARTE VALUES ('TREFLE', '6');
INSERT INTO CARTE VALUES ('TREFLE', '7');
INSERT INTO CARTE VALUES ('TREFLE', '8');
INSERT INTO CARTE VALUES ('TREFLE', '9');
INSERT INTO CARTE VALUES ('TREFLE', '10');
INSERT INTO CARTE VALUES ('TREFLE', 'VALET');
INSERT INTO CARTE VALUES ('TREFLE', 'DAME');
INSERT INTO CARTE VALUES ('TREFLE', 'ROI');


INSERT INTO CARTE VALUES ('CARREAU', '1');
INSERT INTO CARTE VALUES ('CARREAU', '2');
INSERT INTO CARTE VALUES ('CARREAU', '3');
INSERT INTO CARTE VALUES ('CARREAU', '4');
INSERT INTO CARTE VALUES ('CARREAU', '5');
INSERT INTO CARTE VALUES ('CARREAU', '6');
INSERT INTO CARTE VALUES ('CARREAU', '7');
INSERT INTO CARTE VALUES ('CARREAU', '8');
INSERT INTO CARTE VALUES ('CARREAU', '9');
INSERT INTO CARTE VALUES ('CARREAU', '10');
INSERT INTO CARTE VALUES ('CARREAU', 'VALET');
INSERT INTO CARTE VALUES ('CARREAU', 'DAME');
INSERT INTO CARTE VALUES ('CARREAU', 'ROI');
*/
